version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /containers/du
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /containers/cu
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /containers/ru
    schedule:
      interval: weekly
